[package]
name = "btfm"
version = "0.16.0"
edition = "2021"
description = "A Discord bot that plays audio clips based on voice chat"
license = "GPL-2.0-or-later"
documentation = "https://docs.rs/btfm/"
readme = "../README.md"
repository = "https://github.com/jeremycline/btfm/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.axum]
version = "0.4"
features = ["headers", "http1", "json", "multipart", "tower-log"]

[dependencies.axum-server]
version = "0.3"
features = ["tls-rustls"]

[dependencies.btfm-api-structs]
path = "../btfm-api-structs"
version = "0.1"

[dependencies.byteorder]
version = "1"

[dependencies.clap]
version = "3.1"
features = ["derive", "cargo", "env", "unicode", "wrap_help"]

[dependencies.chrono]
version = "0.4"

[dependencies.deepspeech]
version = "0.9"

[dependencies.futures]
version = "0.3"
[dependencies.futures-channel]
version = "0.3"

[dependencies.futures-util]
version = "0.3"

[dependencies.hound]
version = "3"

[dependencies.httparse]
version = "1"

[dependencies.hyper]
version = "0.14"
features=["full"]

[dependencies.once_cell]
version = "1"

[dependencies.rand]
version = "0.8"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[dependencies.serenity]
version = "0.10"
features=["cache", "framework", "gateway", "standard_framework", "http", "rustls_backend", "voice", "utils"]

[dependencies.songbird]
version = "0.2.0"
features=["default", "builtin-queue"]

[dependencies.sqlx]
version = "0.5"
features=["runtime-tokio-rustls", "postgres", "chrono", "migrate", "macros", "uuid"]

[dependencies.tempfile]
version = "3"

[dependencies.thesaurus]
version = "0.2"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
features=["env-filter"]

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1"
features=["full"]

[dependencies.tokio-tungstenite]
version = "0.17"
features = ["rustls"]

[dependencies.tokio-stream]
version = "0.1"

[dependencies.toml]
version = "0.5"

[dependencies.tower]
version = "0.4"

[dependencies.tower-http]
version = "0.2"
features = ["trace", "request-id", "util", "add-extension", "auth", "compression-full", "sensitive-headers"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.ulid]
version = "0.5"
features = ["serde", "uuid"]

[dependencies.uuid]
version = "0.8"
