[package]
name = "btfm"
version = "0.14.2"
edition = "2021"
description = "A Discord bot that plays audio clips based on voice chat"
license = "GPL-2.0-or-later"
documentation = "https://docs.rs/btfm/"
readme = "../README.md"
repository = "https://github.com/jeremycline/btfm/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {"version" = "0.4", features=["headers", "http1", "json", "multipart", "tower-log"]}
byteorder = "1"
clap = "2"
chrono = "0.4"
deepspeech = { "version" = "0.9" }
futures = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
hound = "3"
httparse = "1"
hyper = {"version" = "0.14", features=["full"]}
once_cell = "1"
rand = "0.8"
serde = { "version" = "1", features = ["derive"] }
serde_json = "1"
serenity = {"version" = "0.10", features=["cache", "framework", "gateway", "standard_framework", "http", "rustls_backend", "voice", "utils"] }
structopt = "0.3"
songbird = {"version" = "0.2.0", features=["default", "builtin-queue"]}
sqlx = {"version" = "0.5", features=["runtime-tokio-rustls", "postgres", "chrono", "migrate", "macros", "uuid"]}
tempfile = "3"
thesaurus = "0.2"
tracing = "0.1"
tracing-subscriber = {"version" = "0.3", features=["env-filter"]}
thiserror = "1.0"
tokio = { "version" = "1", features=["full"] }
tokio-tungstenite = { "version" = "0.16", features = ["rustls"] }
tokio-stream = "0.1"
toml = "0.5"
tower-http = { "version" = "0.2", features = ["trace"] }
url = { "version" = "2", features = ["serde"] }
ulid = { "version" = "0.5", features = ["serde", "uuid"] }
uuid = "0.8"
