[package]
name = "btfm"
version = "0.11.0"
authors = ["Jeremy Cline", "Randy Barlow", "Brotivator"]
edition = "2018"
description = "A Discord bot that plays audio clips based on voice chat"
license = "GPL-2.0-or-later"
documentation = "https://docs.rs/btfm/"
readme = "README.md"
repository = "https://github.com/jeremycline/btfm/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { "version" = "1" }
deepspeech = "0.9"
structopt = "0.3"
log = "0.4"
stderrlog = "0.4"
chrono = "0.4"
rand = "0.7"
songbird = "0.1"
byteorder = "1"
thiserror = "1.0"
sqlx = {"version" = "0.5", features=["runtime-tokio-rustls", "postgres", "chrono", "migrate", "macros"]}

[dependencies.audrey]
features = ["wav"]
version = "0.3"

[dependencies.serenity]
version = "0.10"
features = ["cache", "framework", "gateway", "standard_framework", "http", "rustls_backend", "voice", "utils"]

[dev-dependencies]
rand = {version = "0.7", features = ["small_rng"]}
rand_core = "0"

[profile.release]
lto = true
codegen-units = 1
