[package]
name = "btfm"
version = "0.1.0"
authors = ["jcline"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepspeech = "0.6"

[dependencies.audrey]
features = ["wav"]
version = "0.2"

[dependencies.serenity]
features = ["cache", "framework", "gateway", "standard_framework", "http", "native_tls_backend", "voice"]
version = "0.8"
