CREATE TABLE IF NOT EXISTS "clips" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "created_on" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "last_played" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "plays" INTEGER NOT NULL DEFAULT 0,
    "phrase" VARCHAR(1024) NOT NULL,
    "description" TEXT NOT NULL,
    "audio_file" VARCHAR(256) NOT NULL
);