name: Pull request checks

on:
  pull_request:
    branches:
      - master

jobs:
  code_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check -l

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          curl -sOL https://github.com/mozilla/DeepSpeech/releases/download/v0.6.1/native_client.amd64.cpu.linux.tar.xz
          unxz native_client.amd64.cpu.linux.tar.xz
          tar -xf native_client.amd64.cpu.linux.tar
          sudo cp libdeepspeech.so /usr/local/lib/
          sudo ldconfig
      - uses: actions-rs/cargo@v1
        with:
          command: build