---
name: Release
on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: feature or bugfix release
        options:
          - feature
          - bugfix
        required: true
      crate:
        type: choice
        description: which workspace member to release
        options:
          - btfm
          - btfm-cli
          - btfm-api-structs
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          mkdir deepspeech
          pushd deepspeech
          curl -sOL https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/native_client.amd64.cpu.linux.tar.xz
          unxz native_client.amd64.cpu.linux.tar.xz
          tar -xf native_client.amd64.cpu.linux.tar
          sudo cp libdeepspeech.so /usr/local/lib/
          sudo ldconfig
          popd
          rm -rf deepspeech

          sudo apt install postgresql postgresql-contrib
          sudo systemctl restart postgresql.service
          sudo -u postgres createuser btfm
          sudo -u postgres createdb btfm
          sudo -u postgres psql -c "ALTER USER btfm PASSWORD 'password';"
          sudo -u postgres psql -c "ALTER DATABASE btfm OWNER to btfm;"
          export DATABASE_URL=postgres://btfm:password@localhost/btfm
          echo "DATABASE_URL=$DATABASE_URL" >> $GITHUB_ENV
          cargo install cargo-edit
          cargo install sqlx-cli
          cargo sqlx database setup --source btfm/migrations/

      - name: Tag release
        run: |
          set -x

          CURRENT_RELEASE="${{ github.event.inputs.crate }}"-v"$(grep "^version.=." "${{ github.event.inputs.crate }}"/Cargo.toml | awk '{gsub("\"", ""); print $3}')"
          if [ "${{ github.event.inputs.release_type }}" == "feature" ]; then
            cargo set-version --bump minor
          else
            cargo set-version --bump patch
          fi
          NEW_RELEASE="${{ github.event.inputs.crate }}"-v"$(grep "^version.=." "${{ github.event.inputs.crate }}"/Cargo.toml | awk '{gsub("\"", ""); print $3}')"

          git add --all
          git commit -m "$NEW_RELEASE"
          printf "# %s\n\n" "$NEW_RELEASE" > changelog
          printf "# Changes since %s\n\n" "$CURRENT_RELEASE" >> changelog
          git diff --stat "$CURRENT_RELEASE".. >> changelog
          git tag --annotate --file changelog "$NEW_RELEASE"
          git push origin main "$NEW_RELEASE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: changelog
          tag_name: ${{ env.TAG }}
          generate_release_notes: true

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        uses: actions-rs/cargo@v1
        with:
          command: publish -p ${{ github.event.inputs.crate }}

      - name: Create documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items --no-deps

      - name: Bundle up the docs for Randy
        run: tar cvzf btfm-docs.tar.gz target/doc

      - name: Create release build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --profile=production

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/production/"${{ github.event.inputs.crate }}"
            ./the-docs.tar.gz
